### ISSUE TITLE
changed how we arbitrarily choose candidates for trait goals

### ISSUE THREAD

**Issue by lcnr** [rust-lang/trait-system-refactor-initiative#11]
The old solver prioritizes non-global param-env candidates over other candidates.

This is different in the new solver which only prioritizes param-env candidates if they do not guide type inference. This is may break code due to inference changes.

We also disable this behavior during coherence as that would be incomplete. Need some examples where this break stable code.

**Comment by compiler-errors** [comment]
Noting here that we actually prefer alias and param-env bounds now, and we prefer them even if they guide inference, per #111473.

**Comment by lcnr** [comment]
moved into #18
