### ISSUE TITLE
ambiguity due to "maybe-rigid" rigid assoc type

### ISSUE THREAD

**Issue by lcnr** [rust-lang/trait-system-refactor-initiative#111]
- cc https://github.com/rust-lang/trait-system-refactor-initiative/issues/89

```rust
trait Trait<'a> {
    type Assoc;
}

trait Outer<'a>{}

impl<'a, T: ?Sized> Outer<'a> for T
where
    T: Trait<'a>,
    T::Assoc: Trait<'a>,
{}
```
checking `T::Assoc: Trait<'a>`, we try to normalize the self type
- this tries to prove `T: Trait<'a>` either *when checking for wf for coinduction(?)*, or currently in `discard_impls_shadowed_by_env`
  - two `ParamEnv` candidates, `T: Trait<'a>` and `T::Assoc: Trait<'a>`
     - `T: Trait<'a>` holds, but adds a region constraint due to uniquification
     - `T::Assoc: Trait<'a>` may hold if `T::Assoc` normalizes to `T`
        - this causes an inductive cycle

**Comment by compiler-errors** [comment]
fixing this will probably fix #109

**Comment by lcnr** [comment]
this does not affect a test which uses an impl as indirection, as we prefer param env candidates over impls
```rust
trait IntoIterator<'a> {
    type IntoIter;
}

trait Iterator<'a> {}
impl<'a, T: Iterator<'a>> IntoIterator<'a> for T {
    type IntoIter = T;
}

trait Outer<'a>{}

impl<'a, T: ?Sized> Outer<'a> for T
where
    T: IntoIterator<'a>,
    T::IntoIter: Iterator<'a>,
{}
```

**Comment by lcnr** [comment]
closing due to https://github.com/rust-lang/trait-system-refactor-initiative/issues/114#issuecomment-2123832503
