### ISSUE TITLE
instantiate query response nested obligations

### ISSUE THREAD

**Issue by lcnr** [rust-lang/trait-system-refactor-initiative#21]
While instantiating a query response we may end up emitting nested obligations.

This is annoying and we have to deal with them somehow. We currently put them into the fulfillment context of the caller, but that may not be great for diagnostics. I think we could alternatively loop tem in a separate context while instantiating and `OR` their certainty with the main goal

**Comment by compiler-errors** [comment]
For coherence: we already do this in `evaluate_predicate` so it's not unsound at least :^).

**Comment by lcnr** [comment]
with https://github.com/rust-lang/rust/pull/119106 instantiating query responses does not result in nested obligations anymore. Closing
