### ISSUE TITLE
weaker leak-check in new solver

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/trait-system-refactor-initiative#34]
The new solver breaks the following:
```rust
trait Leak<'a> {}
impl Leak<'_>      for Box<u32> {}
impl Leak<'static> for Box<u16> {}

fn impl_trait<T: for<'a> Leak<'a>>() {}

fn main() {
    impl_trait::<Box<_>>();
    //~^ ERROR type annotations needed
}
```

This needs investigation. The old and new solvers share the same leak-check logic. They shouldn't behave differently.

**Comment by compiler-errors** [comment]
This has to do with region uniquification on query input.

`for<'a> Box<?0>: Leak<'a>` gets instantiated with placeholders like `Box<?0>: Leak<'!1_0>` (placeholder in universe 1). But that gets canonicalized and uniquified to `Box<?0>: Leak<'?0_0>` (re vid in universe 0). The ambiguity occurs because we've totally erased all region information, we can't actually use the leak check to disqualify the `Leak<'static>` candidate at this point.

**Comment by aliemjay** [comment]
Then I think the leak check should be done in [`merge_candidates`](https://github.com/rust-lang/rust/blob/fe37f37e4b764bb82fc0eb8c727842746de7c93f/compiler/rustc_trait_selection/src/solve/assembly/mod.rs#L738). This way this issue is fixed and we would have an arguably more reasonable location to invoke the leak check than in `compute_external_query_constraints`.

At this point, we can change the the leak checker to construct the constraint graph directly from the canonical response in order to avoid the overhead of entering a new snapshot and instantiating the query response for each candidate.

**Comment by compiler-errors** [comment]
I'm not sure if I understand how moving the leak check to `merge_candidates` would fix this issue. This has to do with the fact that we erase the universe region in canonicalization, and as long as we're canonicalizing nested obligations, we can always push this issue one layer deeper into the goal stack, e.g.

```
trait Leak2<'a> {}
impl Leak2<'_>      for Box<u32> {}
impl Leak2<'static> for Box<u16> {}

trait Leak1<'a> {}
impl<'a, T> Leak1<'a> for T where T: Leak2<'a> {} 

fn impl_trait<T: for<'a> Leak1<'a>>() {}

fn main() {
    impl_trait::<Box<_>>();
    //~^ ERROR type annotations needed
}
```

**Comment by lcnr** [comment]
accepted as part of #119820
