### ISSUE TITLE
Inductive cycles are treated as ambiguous in new solver, failure in old solver

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/trait-system-refactor-initiative#50]
Minimized from #113895 (`interval-map`):

```rust
use std::borrow::Borrow;
use std::cmp::Ordering;
use std::marker::PhantomData;

#[derive(PartialEq, Default)]
pub(crate) struct Interval<T>(PhantomData<T>);

impl<T, Q> PartialEq<Q> for Interval<T>
where
    T: Borrow<Q>,
    Q: ?Sized + PartialOrd,
{
    fn eq(&self, other: &Q) -> bool {
        true
    }
}

impl<T, Q> PartialOrd<Q> for Interval<T>
where
    T: Borrow<Q>,
    Q: ?Sized + PartialOrd,
{
    fn partial_cmp(&self, other: &Q) -> Option<Ordering> {
        None
    }
}
```

This code **passes in the old solver, fails in the new solver**. 

That's because when checking if the `PartialEq` impls overlap (one from the `Derive` and one from the manual impl), we check if any of the [predicates fail hold](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_trait_selection/traits/coherence/fn.impl_intersection_has_impossible_obligation.html). This means we try checking `Interval<?1>: PartialOrd<Interval<?1>>`, which ends up being an inductive cycle with itself. Inductive cycles are treated as [not holding](https://github.com/rust-lang/rust/blob/8771282d4e7a5c4569e49d1f878fb3ba90a974d0/compiler/rustc_middle/src/traits/select.rs#L276) in the old solver, since they are [evaluated to `EvaluatedToRecur`](https://github.com/rust-lang/rust/blob/8771282d4e7a5c4569e49d1f878fb3ba90a974d0/compiler/rustc_trait_selection/src/traits/select/mod.rs#L723). Meanwhile, inductive cycles in the new trait solver are treated as ambiguous.

**Comment by lcnr** [comment]
forgot this this issue can also be used in coherence :/ anyways, already have #20, so moved the example to that issue
