### ISSUE TITLE
Ambiguity, differing outlives constraints with types equal modulo normalization

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/trait-system-refactor-initiative#57]
```rust
fn main() {
    let _: &dyn Iterator<Item=i32> = &vec![1].into_iter();
}
```

When coercing `&'?0 <Vec<{integer}> as IntoIterator>::IntoIter` into `&'?1 dyn Iterator<Item=i32>`, we end up with two responses.

The first has a type-outlives constraint like `<Vec<{integer}> as IntoIterator>::IntoIter: &'?1`, and the second has one like `std::vec::IntoIter<{integer}>: &'?1`. These are identical except for their types being normalized, but that causes us to flounder.

**Comment by compiler-errors** [comment]
Interestingly, the code with `Box` doesn't fail because the `Box::new` constructor causes the type to be normalized due to the argument being a coercion point:

```rust
fn main() {
    let _: Box<dyn Iterator<Item=i32> + '_> = Box::new(vec![1].into_iter());
}
```

**Comment by compiler-errors** [comment]
This may be a problem somewhat specific to `T -> dyn Trait` unsizing -- we could perhaps consider those goals separately within `assemble_blanket_impl_candidates`, and not in `assemble_candidates_via_self_ty`.

**Comment by lcnr** [comment]
I think we should consider the three way split of "assemble blanket candidates", "assemble_normalization_step_candidates" and "assemble_candidates_via_self_ty" or whatever
