### ISSUE TITLE
opaque auto trait leakage in coherence

### ISSUE THREAD

**Issue by lcnr** [rust-lang/trait-system-refactor-initiative#65]
we should add tests that we don't leak auto traits of opaques in coherence and update the impl to make sure that we don't

**Comment by compiler-errors** [comment]
This can never happen currently because we always hit ambiguity when normalizing a TAIT during candidate assembly. We probably should protect against it regardless, but I don't think we have any tests that are unsound currently.

I couldn't think of a more creative test than this tho:

```
#![feature(type_alias_impl_trait)]

mod foo {
    type Tait = impl Sized;

    pub struct Wrapper(Tait);

    fn test() -> Tait { std::ptr::null_mut::<()>() }
}

trait Foo {}

impl<T: Send> Foo for T {}

impl Foo for foo::Wrapper {}
//~^ ERROR conflict implementations of trait `Foo` for type `Wrapper`
```

**Comment by lcnr** [comment]
closing due to https://github.com/rust-lang/rust/pull/116689
