### ISSUE TITLE
alias-bounds for normalizable alias + deeply normalize ~> MIR typeck ICE

### ISSUE THREAD

**Issue by lcnr** [rust-lang/trait-system-refactor-initiative#77]
```rust
trait Trait {
    type Assoc: Clone;
}

fn is_clone<T: Clone>(_: *mut T) {}

fn foo<T: Trait<Assoc = U>, U>(x: *mut <T as Trait>::Assoc) {
    is_clone(x);
}
```
https://rust.godbolt.org/z/4WojT7KTW

This currently results in an ICE:
- in HIR typeck `<T as Trait>::Assoc: Clone` holds due to the alias bound candidate
- during writeback we deeply normalize, replacing `<T as Trait>::Assoc` with `U`
- MIR typeck checks `U: Clone` which does not hold, resulting in an ICE

**Comment by lcnr** [comment]
the easiest fix is to change `assemble_candidates_after_normalizing_self_ty` to only assemble candidates for a fully normalized type by switching it to use `try_normalize_ty` 🤔 this matches the behavior of the old solver and should avoid deeply normalizing from erasing relevant info

**Comment by compiler-errors** [comment]
> the easiest fix is to change assemble_candidates_after_normalizing_self_ty to only assemble candidates for a fully normalized type by switching it to use try_normalize_ty

:( incompleteness
