### ISSUE TITLE
Normalizes-to overflow with rigid alias with redundant bound

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/trait-system-refactor-initiative#83]
```rust
pub fn choice<I>(iter: I) -> Option<I::Item>
where
    I: IntoIterator,
    I::IntoIter: Iterator,
{
    todo!()
}
```

```
error[E0275]: overflow evaluating the requirement `<I as IntoIterator>::Item normalizes-to _`
 --> <source>:1:30
  |
1 | pub fn choice<I>(iter: I) -> Option<I::Item>
  |                              ^^^^^^^^^^^^^^^
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`example`)
```

**Comment by compiler-errors** [comment]
extracted from fastrand crate

**Comment by lcnr** [comment]
Think this is https://github.com/rust-lang/trait-system-refactor-initiative/issues/76

normalizing `<I as IntoIterator>::Item` uses the `impl<T: Iterator> IntoIterator for T` impl, I guess that tries to prove `I: Iterator` which tries `alias-relate(I, <I as IntoIterator>::IntoIter>)` which has to normalize `<I as IntoItertor>::IntoIter` at which point we get a cycle
